---
abstract: "Perl interface to Goole's libphonenumber"
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires:
  Number::Phone::Formatter::Raw: '0'
  Socket: '0'
  Test::More: '0'
configure_requires:
  Devel::CheckLib: '0'
  ExtUtils::CppGuess: '0'
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.006, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Number-LibPhoneNumber
requires:
  Exporter: '0'
  XSLoader: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Number-LibPhoneNumber
  homepage: http://search.cpan.org/dist/Number-LibPhoneNumber/
  repository: git://github.com/mschout/perl-number-libphonenumber.git
version: '0.01'
x_serialization_backend: 'YAML::Tiny version 1.63'
